// Shared merge logic for baking editor snapshots into src/core/defaults.js.
// Used both by the Vite dev-server /__bake endpoint and by the standalone
// scripts/bake-defaults.mjs CLI fallback.

export function mergeLevels(oldLevels, newLevels) {
  if (!newLevels) return oldLevels;
  if (!oldLevels) return newLevels;
  const out = {};
  for (const k of Object.keys(oldLevels)) if (k !== "_gone") out[k] = oldLevels[k];
  for (const k of Object.keys(newLevels)) if (k !== "_gone") out[k] = newLevels[k];
  const gone = new Set([...(oldLevels._gone || []), ...(newLevels._gone || [])]);
  out._gone = [...gone];
  return out;
}

export function mergeFlat(oldObj, newObj) {
  if (!newObj) return oldObj || null;
  if (!oldObj) return newObj;
  return { ...oldObj, ...newObj };
}

export function mergeBaked(existing, dump) {
  const base = existing || {
    levels: null, params: null, settings: null, score: null, mix: null, talk: null, intro: null, tiles: null
  };
  return {
    savedAt: dump.savedAt || Date.now(),
    levels: mergeLevels(base.levels, dump.levels),
    params: mergeFlat(base.params, dump.params),
    settings: mergeFlat(base.settings, dump.settings),
    score: dump.score || base.score || null,
    mix: mergeFlat(base.mix, dump.mix),
    talk: mergeFlat(base.talk, dump.talk),
    intro: dump.intro != null ? dump.intro : (base.intro || null),
    tiles: dump.tiles != null ? dump.tiles : (base.tiles || null)
  };
}

export function parseDefaultsSource(src) {
  const marker = "export var BAKED = ";
  const i = String(src).indexOf(marker);
  if (i < 0) return null;
  const start = src.indexOf("{", i);
  if (start < 0) return null;
  let depth = 0, inStr = false, esc = false;
  for (let p = start; p < src.length; p++) {
    const c = src[p];
    if (inStr) {
      if (esc) { esc = false; continue; }
      if (c === "\\") { esc = true; continue; }
      if (c === "\"") inStr = false;
      continue;
    }
    if (c === "\"") { inStr = true; continue; }
    if (c === "{") depth++;
    else if (c === "}") {
      depth--;
      if (depth === 0) return JSON.parse(src.slice(start, p + 1));
    }
  }
  return null;
}

export function formatDefaults(merged) {
  return [
    "// Auto-generated by the editor (vite /__bake) or `npm run bake` — do not hand-edit.",
    "// Shipped snapshot: levels (persist.js), physics params, optional settings/mix/talk/intro.",
    "// Per-browser localStorage is a draft overlay; newer savedAt wins (see persist.preferLocal).",
    `export var BAKED = ${JSON.stringify(merged, null, 2)};`,
    ""
  ].join("\n");
}
